import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ClipboardCheck, Factory, FileSearch, Gauge, Map, ShieldCheck, Wrench } from "lucide-react";
import { WorkflowAuditViewTracker } from "@/components/conversion-tracker";
import { ThemeToggle } from "@/components/theme-toggle";
import { WorkflowAuditBookingLink, WorkflowAuditForm } from "@/components/workflow-audit-form";
import { Card, CardContent } from "@/components/ui/card";
import { workflowAuditBookingURL } from "@/lib/workflow-audit-config";

export const metadata: Metadata = {
  title: "Workflow Audit",
  description: "A focused paid operational review for businesses struggling with quoting, inventory, scheduling, paperwork, production visibility, or disconnected tools.",
  alternates: { canonical: "/workflow-audit" },
  openGraph: { title: "Workflow Audit · 4TWENTY.DEV", description: "Find where operational work is getting stuck and leave with a practical, prioritized improvement plan.", url: "/workflow-audit" },
};

const friction = ["Quoting delays", "Inventory uncertainty", "Scheduling conflicts", "Duplicate paperwork", "Production visibility", "Disconnected tools"];
const process = [
  ["01", "Focused intake", "You describe the workflow, tools, handoffs, and operating pain without uploading sensitive business files."],
  ["02", "Review conversation", "Brandon traces how the work actually moves, where decisions stall, and what constraints a useful fix must respect."],
  ["03", "Operational assessment", "The workflow is separated into friction, risk, repeated effort, information gaps, and practical intervention points."],
  ["04", "Actionable handoff", "You receive a concise prioritized plan—not a generic software pitch or an automatic commitment to a larger build."],
];
const deliverables = [
  [Map, "Workflow map", "A plain-language view of the current process, handoffs, and failure points."],
  [FileSearch, "Friction assessment", "The highest-leverage delays, duplicate work, uncertainty, and owner dependencies."],
  [Wrench, "Improvement options", "Practical changes across process, existing tools, automation, or focused software."],
  [ClipboardCheck, "Prioritized next steps", "A sequenced recommendation with assumptions, constraints, and what should be validated first."],
];

export default function WorkflowAuditPage() {
  const bookingURL = workflowAuditBookingURL();
  return <main className="min-h-screen overflow-hidden"><WorkflowAuditViewTracker /><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_70%_0%,color-mix(in_oklab,var(--primary)_16%,transparent),transparent_38%)]" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="font-mono text-xs font-semibold tracking-[0.24em]">4TWENTY<span className="text-primary">.DEV</span></Link><div className="flex items-center gap-2"><ThemeToggle /><Link href="/" className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs text-muted-foreground transition hover:text-foreground"><ArrowLeft className="size-3.5" />Home</Link></div></header>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Paid operational review</div><h1 className="mt-4 max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-0.055em] sm:text-7xl">Find where the work is getting stuck.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">A Workflow Audit is a focused evaluation for businesses losing time to quoting, inventory, scheduling, paperwork, production uncertainty, or tools that do not talk to each other.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#audit-intake" className="inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">Start the intake <ArrowRight className="size-4" /></a>{bookingURL ? <WorkflowAuditBookingLink href={bookingURL} className="inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-card px-5 text-sm font-medium" /> : null}</div><p className="mt-4 max-w-xl text-xs leading-5 text-muted-foreground">This is a paid consultation. Fit, scope, fee, and timing are confirmed directly before anything is booked. No payment is collected on this site.</p></div>
      <Card className="bg-card/80 shadow-2xl backdrop-blur"><CardContent className="p-6 sm:p-8"><div className="flex items-center justify-between border-b border-border pb-5"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Good audit signal</div><div className="mt-1 text-sm font-medium">The operation has friction you can feel but cannot clearly isolate.</div></div><Gauge className="size-5 shrink-0 text-primary" /></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{friction.map((item, index) => <div key={item} className="flex items-center gap-3 rounded-lg border border-border bg-background/50 px-3 py-3 text-sm"><span className="font-mono text-[9px] text-primary">0{index + 1}</span>{item}</div>)}</div></CardContent></Card>
    </section>
    <section className="relative border-y border-border bg-card/35"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="mb-10 max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">The process</div><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A short path from operating pain to a useful decision.</h2></div><div className="grid border-y border-border lg:grid-cols-4">{process.map(([number, title, description], index) => <div key={title} className="border-t border-border py-6 first:border-t-0 lg:border-l lg:border-t-0 lg:px-6 lg:first:border-l-0 lg:first:pl-0"><span className="font-mono text-[9px] text-primary">{number}</span><h3 className="mt-5 text-base font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p>{index === 3 ? <span className="mt-5 inline-flex items-center gap-2 text-xs text-primary"><ShieldCheck className="size-3.5" />No forced implementation sale</span> : null}</div>)}</div></div></section>
    <section className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Deliverables</div><h2 className="mt-3 text-3xl font-semibold tracking-tight">What you leave with.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">The audit is designed to make the next decision clearer, whether that means changing a process, using an existing tool better, testing an automation, or scoping a focused build.</p></div><div className="grid gap-3 sm:grid-cols-2">{deliverables.map(([Icon, title, description]) => <Card key={title as string} className="bg-card/60"><CardContent className="p-6"><Icon className="size-5 text-primary" /><h3 className="mt-7 text-base font-medium">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description as string}</p></CardContent></Card>)}</div></div></section>
    <section id="audit-intake" className="relative border-t border-border bg-card/35"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.55fr_1.45fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Qualification intake</div><h2 className="mt-3 text-3xl font-semibold tracking-tight">Start with the messy version.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Share enough to understand the operating problem. Do not include passwords, customer data, financial records, proprietary drawings, or production files.</p><div className="mt-7 space-y-3 border-t border-border pt-6 text-xs leading-5 text-muted-foreground"><p className="flex gap-2"><Factory className="mt-0.5 size-3.5 shrink-0 text-primary" />Best fit: small manufacturers, fabrication shops, contractors, field-service teams, and owner-led operations.</p><p className="flex gap-2"><ShieldCheck className="mt-0.5 size-3.5 shrink-0 text-primary" />Submissions go to a private owner-only lead pipeline and are not used for advertising.</p></div></div><Card className="bg-background/75"><CardContent className="p-6 sm:p-8"><WorkflowAuditForm bookingURL={bookingURL} /></CardContent></Card></div></section>
    <footer className="relative border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 text-xs text-muted-foreground sm:flex-row"><span>© {new Date().getFullYear()} 4TWENTY.DEV</span><span className="font-mono text-[9px] uppercase tracking-[0.18em]">Workflow clarity before software</span></div></footer>
  </main>;
}
