import Link from "next/link";
import { ArrowRight, Blocks, CircuitBoard, Code2, Factory, Gauge, Github, Layers3, Mail, MoveUpRight, ScanLine, ShieldCheck } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { ThemeToggle } from "@/components/theme-toggle";

const services = [
  { icon: Code2, title: "Custom software", text: "Purpose-built web applications, client portals, and internal command centers." },
  { icon: CircuitBoard, title: "Workflow automation", text: "Connect the repetitive parts of your operation so the important work moves faster." },
  { icon: Factory, title: "Digital fabrication", text: "CNC, signage, quoting, inventory, and shop-floor systems shaped around real production." },
  { icon: Blocks, title: "Rapid prototyping", text: "Turn a rough idea into a testable product without dragging it through a bloated process." },
];

const studies = [
  { number: "01", stage: "Live system", title: "WORK//CTRL", kicker: "Personal operations platform", description: "A secure command center that brings projects, tasks, GitHub activity, deployment health, planning, notes, and reminders into one operating view.", stack: ["Next.js", "Neon", "Passkeys", "Vercel"], signal: "From scattered tools to one daily control surface", icon: Gauge },
  { number: "02", stage: "Active concept", title: "SignForge", kicker: "CNC signage workflow", description: "A production-minded system for taking custom sign work from customer intent through design decisions, material planning, fabrication, and delivery.", stack: ["CNC", "Quoting", "Production", "Automation"], signal: "Built around the shop floor—not generic project management", icon: ScanLine },
  { number: "03", stage: "Prototype", title: "Shop Inventory", kicker: "Operational visibility", description: "A lightweight inventory and replenishment concept designed to answer what is on hand, what is committed, and what needs attention without spreadsheet archaeology.", stack: ["Inventory", "Mobile", "Workflows", "Reporting"], signal: "Clear next actions from real operating data", icon: Layers3 },
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_75%_0%,color-mix(in_oklab,var(--primary)_15%,transparent),transparent_38%)]" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="font-mono text-xs font-semibold tracking-[0.24em]">4TWENTY<span className="text-primary">.DEV</span></Link><nav className="flex items-center gap-1 sm:gap-2"><Link href="#services" className="hidden px-3 py-2 text-xs text-muted-foreground hover:text-foreground sm:block">Services</Link><Link href="#work" className="hidden px-3 py-2 text-xs text-muted-foreground hover:text-foreground sm:block">Work</Link><Link href="#contact" className="hidden px-3 py-2 text-xs text-muted-foreground hover:text-foreground sm:block">Contact</Link><ThemeToggle /><Link href="/login" className="rounded-lg border border-border bg-card px-3 py-2 text-xs font-medium transition hover:border-primary/40">Command Center</Link></nav></header>
    <section className="relative mx-auto grid min-h-[72vh] max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.2em] text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Independent builder · Denver, Colorado</div><h1 className="max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-0.055em] sm:text-7xl">Useful systems for<br /><span className="text-primary">real-world work.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">I design and build focused software, automation, and digital-fabrication tools for businesses that have outgrown spreadsheets and workarounds.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#contact" className="inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">Start a conversation <ArrowRight className="size-4" /></Link><Link href="#work" className="inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-card px-5 text-sm font-medium">See selected work</Link></div></div>
      <div className="relative"><div className="absolute -inset-10 bg-primary/10 blur-3xl" /><Card className="relative overflow-hidden bg-card/85 shadow-2xl backdrop-blur"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between border-b border-border pb-4"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Build signal</div><div className="mt-1 text-sm font-medium">4TWENTY // capabilities</div></div><Gauge className="size-5 text-primary" /></div>{["Software that fits the operation", "Automation without the busywork", "Production-minded design", "Direct access to the builder"].map((item, index) => <div key={item} className="flex items-center gap-3 border-b border-border/60 py-4 last:border-0"><span className="font-mono text-[9px] text-muted-foreground">0{index + 1}</span><span className="flex-1 text-sm">{item}</span><span className="size-1.5 rounded-full bg-emerald-400" /></div>)}</CardContent></Card></div></section>
    <section id="services" className="relative border-y border-border bg-card/35"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mb-10 max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Services</div><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">From stubborn problem to working system.</h2></div><div className="grid gap-3 md:grid-cols-2">{services.map(({ icon: Icon, title, text }) => <Card key={title} className="group bg-background/60 transition hover:border-primary/30"><CardContent className="p-6"><Icon className="size-5 text-primary" /><h3 className="mt-8 text-lg font-medium">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{text}</p></CardContent></Card>)}</div></div></section>
    <section id="work" className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Selected work</div><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Systems with an operating point of view.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">A mix of live builds, prototypes, and active concepts. Each starts with the workflow—not a generic template looking for a use.</p></div><a href="https://github.com/4twentydev" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-muted-foreground transition hover:text-foreground"><Github className="size-4" />View GitHub <MoveUpRight className="size-3.5" /></a></div><div className="space-y-4">{studies.map(({ number, stage, title, kicker, description, stack, signal, icon: Icon }) => <Card key={title} className="group overflow-hidden bg-card/70 transition hover:border-primary/30"><CardContent className="grid gap-6 p-6 md:grid-cols-[80px_1fr_.8fr] md:items-center md:p-8"><div className="flex items-center justify-between md:block"><span className="font-mono text-xs text-muted-foreground">{number}</span><div className="mt-0 md:mt-7 grid size-11 place-items-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><Icon className="size-5" /></div></div><div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-primary/20 bg-primary/10 text-primary">{stage}</Badge><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">{kicker}</span></div><h3 className="mt-4 text-2xl font-semibold tracking-tight">{title}</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p><div className="mt-5 flex flex-wrap gap-2">{stack.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div></div><div className="border-t border-border pt-5 md:border-l md:border-t-0 md:pl-7 md:pt-0"><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">Operating signal</div><p className="mt-3 text-sm font-medium leading-6">{signal}</p><ArrowRight className="mt-5 size-4 text-primary transition group-hover:translate-x-1" /></div></CardContent></Card>)}</div></section>
    <section id="contact" className="relative border-t border-border bg-card/35"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Open channel</div><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Have a problem worth fixing?</h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">Share the messy version. A useful first conversation is about the current workflow, where it breaks, and what better would actually mean.</p><div className="mt-8 space-y-3 text-sm"><div className="flex items-center gap-3"><ShieldCheck className="size-4 text-primary" />Direct and confidential</div><div className="flex items-center gap-3"><Mail className="size-4 text-primary" /><a href="mailto:hello@4twenty.dev" className="hover:text-primary">hello@4twenty.dev</a></div></div></div><Card className="bg-background/70"><CardContent className="p-6 sm:p-8"><ContactForm /></CardContent></Card></div></section>
    <footer className="relative border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 text-xs text-muted-foreground sm:flex-row"><span>© {new Date().getFullYear()} 4TWENTY.DEV</span><span className="font-mono text-[9px] uppercase tracking-[0.18em]">Software · automation · fabrication</span></div></footer>
  </main>;
}
