import Link from "next/link";
import { ArrowRight, Blocks, CircuitBoard, Code2, Factory, Gauge, Mail } from "lucide-react";
import { ThemeToggle } from "@/components/theme-toggle";

const services = [
  { icon: Code2, title: "Custom software", text: "Purpose-built web applications, client portals, and internal command centers." },
  { icon: CircuitBoard, title: "Workflow automation", text: "Connect the repetitive parts of your operation so the important work moves faster." },
  { icon: Factory, title: "Digital fabrication", text: "CNC, signage, quoting, inventory, and shop-floor systems shaped around real production." },
  { icon: Blocks, title: "Rapid prototyping", text: "Turn a rough idea into a testable product without dragging it through a bloated process." },
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_75%_0%,color-mix(in_oklab,var(--primary)_15%,transparent),transparent_38%)]" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="font-mono text-xs font-semibold tracking-[0.24em]">4TWENTY<span className="text-primary">.DEV</span></Link><nav className="flex items-center gap-2"><Link href="#services" className="hidden px-3 py-2 text-xs text-muted-foreground hover:text-foreground sm:block">Services</Link><Link href="#contact" className="hidden px-3 py-2 text-xs text-muted-foreground hover:text-foreground sm:block">Contact</Link><ThemeToggle /><Link href="/login" className="rounded-lg border border-border bg-card px-3 py-2 text-xs font-medium transition hover:border-primary/40">Command Center</Link></nav></header>
    <section className="relative mx-auto grid min-h-[72vh] max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 font-mono text-[9px] uppercase tracking-[0.2em] text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" />Independent builder · Denver, Colorado</div><h1 className="max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-0.055em] sm:text-7xl">Useful systems for<br /><span className="text-primary">real-world work.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">I design and build focused software, automation, and digital-fabrication tools for businesses that have outgrown spreadsheets and workarounds.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#contact" className="inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">Start a conversation <ArrowRight className="size-4" /></Link><Link href="#services" className="inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-card px-5 text-sm font-medium">Explore services</Link></div></div>
      <div className="relative"><div className="absolute -inset-10 bg-primary/10 blur-3xl" /><div className="relative overflow-hidden rounded-2xl border border-border bg-card/85 p-5 shadow-2xl backdrop-blur"><div className="mb-5 flex items-center justify-between border-b border-border pb-4"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Build signal</div><div className="mt-1 text-sm font-medium">4TWENTY // capabilities</div></div><Gauge className="size-5 text-primary" /></div>{["Software that fits the operation", "Automation without the busywork", "Production-minded design", "Direct access to the builder"].map((item, index) => <div key={item} className="flex items-center gap-3 border-b border-border/60 py-4 last:border-0"><span className="font-mono text-[9px] text-muted-foreground">0{index + 1}</span><span className="flex-1 text-sm">{item}</span><span className="size-1.5 rounded-full bg-emerald-400" /></div>)}</div></div></section>
    <section id="services" className="relative border-y border-border bg-card/35"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="mb-10 max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Services</div><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">From stubborn problem to working system.</h2></div><div className="grid gap-3 md:grid-cols-2">{services.map(({ icon: Icon, title, text }) => <article key={title} className="group rounded-xl border border-border bg-background/60 p-6 transition hover:border-primary/30"><Icon className="size-5 text-primary" /><h3 className="mt-8 text-lg font-medium">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>
    <section id="contact" className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="rounded-2xl border border-border bg-card p-8 sm:p-12"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Open channel</div><div className="mt-4 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Have a problem worth fixing?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Tell me what is slowing you down, what you have already tried, and what a useful outcome looks like.</p></div><a href="mailto:hello@4twenty.dev" className="inline-flex h-11 shrink-0 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground"><Mail className="size-4" />hello@4twenty.dev</a></div></div></section>
    <footer className="relative border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 text-xs text-muted-foreground sm:flex-row"><span>© {new Date().getFullYear()} 4TWENTY.DEV</span><span className="font-mono text-[9px] uppercase tracking-[0.18em]">Software · automation · fabrication</span></div></footer>
  </main>;
}
