import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Gauge, Layers3, ScanLine } from "lucide-react";
import type { CaseStudy } from "@/lib/case-studies";
import { Badge } from "@/components/ui/badge";
import { ProjectStatusBadge } from "@/components/project-status-badge";
import { ProjectMediaGallery } from "@/components/project-media";
import { ThemeToggle } from "@/components/theme-toggle";

const icons = { gauge: Gauge, "scan-line": ScanLine, layers: Layers3 };

function NarrativeBlock({ index, label, children }: { index: string; label: string; children: React.ReactNode }) {
  return <section className="grid gap-3 border-t border-border py-7 sm:grid-cols-[52px_170px_1fr]"><span className="font-mono text-[9px] text-primary">{index}</span><h2 className="text-sm font-medium">{label}</h2><div className="max-w-3xl text-sm leading-7 text-muted-foreground">{children}</div></section>;
}

export function CaseStudyDetail({ study, previous, next }: { study: CaseStudy; previous: CaseStudy; next: CaseStudy }) {
  const Icon = icons[study.icon];
  return <main className="min-h-screen overflow-hidden"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_75%_0%,color-mix(in_oklab,var(--primary)_15%,transparent),transparent_38%)]" /><header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="font-mono text-xs font-semibold tracking-[0.24em]">4TWENTY<span className="text-primary">.DEV</span></Link><div className="flex items-center gap-2"><ThemeToggle /><Link href="/#work" className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs text-muted-foreground transition hover:text-foreground"><ArrowLeft className="size-3.5" />Selected work</Link></div></header>
    <article className="relative mx-auto max-w-7xl px-5 pb-24 pt-14 sm:px-8 sm:pt-20"><header className="grid gap-12 border-b border-border pb-16 lg:grid-cols-[1fr_320px] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><ProjectStatusBadge status={study.status} /><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">Project profile {study.number} · {study.kicker}</span></div><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-0.055em] sm:text-7xl">{study.title}</h1><p className="mt-7 max-w-3xl text-base leading-7 text-muted-foreground sm:text-lg">{study.summary}</p></div><div className="border-t border-border pt-6 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><div className="grid size-12 place-items-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><Icon className="size-5" /></div><div className="mt-6 font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">Operating signal</div><p className="mt-3 text-sm font-medium leading-6">{study.signal}</p></div></header>
      <section aria-labelledby="project-media-heading" className="border-b border-border py-12 sm:py-16"><div className="mb-7 grid gap-3 md:grid-cols-[190px_1fr]"><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Product media</div><div><h2 id="project-media-heading" className="text-xl font-semibold tracking-tight">System in view</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Verified product media appears here when available; clearly labeled placeholders identify what still needs to be supplied.</p></div></div><ProjectMediaGallery media={study.media} projectTitle={study.title} /></section>
      <div className="mt-10"><NarrativeBlock index="01" label="Operational problem">{study.problem}</NarrativeBlock><NarrativeBlock index="02" label="Intended for">{study.intendedFor}</NarrativeBlock><NarrativeBlock index="03" label="Previous workflow">{study.previousWorkflow}</NarrativeBlock><NarrativeBlock index="04" label="Solution">{study.solution}</NarrativeBlock><NarrativeBlock index="05" label="Key capabilities"><ul className="grid gap-3 sm:grid-cols-2">{study.capabilities.map((capability) => <li key={capability} className="flex items-start gap-2 text-foreground/85"><CheckCircle2 className="mt-1 size-3.5 shrink-0 text-primary" />{capability}</li>)}</ul></NarrativeBlock><NarrativeBlock index="06" label="Technologies / working stack"><div className="flex flex-wrap gap-2">{study.technologies.map((technology) => <Badge key={technology} variant="secondary">{technology}</Badge>)}</div></NarrativeBlock><NarrativeBlock index="07" label={study.outcomeLabel}><p>{study.outcome}</p></NarrativeBlock><NarrativeBlock index="08" label="Limitations and status"><p>{study.limitations}</p></NarrativeBlock></div>
      <section className="mt-10 grid gap-7 border-y border-border py-9 md:grid-cols-[1fr_auto] md:items-center"><div><div className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Relevant next step</div><h2 className="mt-3 text-2xl font-semibold tracking-tight">Does this resemble a workflow you are carrying manually?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Start with the current process, its constraints, and the decisions that keep returning to the owner.</p></div><Link href={study.cta.href} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">{study.cta.label}<ArrowRight className="size-4" /></Link></section>
      <nav aria-label="More project profiles" className="mt-10 grid gap-3 sm:grid-cols-2"><Link href={`/work/${previous.slug}`} className="rounded-xl border border-border bg-card/60 p-5 transition hover:border-primary/30"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">Previous project</span><span className="mt-3 flex items-center gap-2 text-sm font-medium"><ArrowLeft className="size-4 text-primary" />{previous.title}</span></Link><Link href={`/work/${next.slug}`} className="rounded-xl border border-border bg-card/60 p-5 text-right transition hover:border-primary/30"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">Next project</span><span className="mt-3 flex items-center justify-end gap-2 text-sm font-medium">{next.title}<ArrowRight className="size-4 text-primary" /></span></Link></nav>
    </article><footer className="relative border-t border-border px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-2 text-xs text-muted-foreground sm:flex-row"><span>© {new Date().getFullYear()} 4TWENTY.DEV</span><Link href="/#work" className="font-mono text-[9px] uppercase tracking-[0.18em] hover:text-foreground">All selected work</Link></div></footer></main>;
}
