import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Factory, GitBranch, Globe2, MoveUpRight, ScanLine, Target } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { SiteFooter } from "@/components/site-footer";
import { ThemeToggle } from "@/components/theme-toggle";
import { getCaseStudy } from "@/lib/case-studies";
import { engagementPlanningNote } from "@/lib/engagements";
import type { PublicService } from "@/lib/services";
import { publicServices } from "@/lib/services";

const icons = { factory: Factory, workflow: GitBranch, website: Globe2, "scan-line": ScanLine };

export function ServiceDetail({ service }: { service: PublicService }) {
  const Icon = icons[service.icon];
  const examples = service.caseStudyLinks.map((reference) => ({ ...reference, study: getCaseStudy(reference.slug) })).filter((reference) => reference.study);

  return <main className="min-h-screen overflow-hidden">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_75%_0%,color-mix(in_oklab,var(--primary)_15%,transparent),transparent_38%)]" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <BrandMark />
      <nav aria-label="Primary" className="flex items-center gap-1 sm:gap-2"><Link href="/#services" className="hidden px-3 py-2 text-xs text-muted-foreground transition hover:text-foreground sm:block">Software + automation</Link><Link href="/#work" className="hidden px-3 py-2 text-xs text-muted-foreground transition hover:text-foreground md:block">Work</Link><Link href="/about" className="hidden px-3 py-2 text-xs text-muted-foreground transition hover:text-foreground lg:block">About</Link><ThemeToggle /><Link href={service.cta.href} className="rounded-lg border border-primary/30 bg-primary/10 px-3 py-2 text-xs font-medium text-primary transition hover:bg-primary/15"><span className="sm:hidden">Start</span><span className="hidden sm:inline">Start a conversation</span></Link></nav>
    </header>

    <article className="relative">
      <header className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-14 sm:px-8 sm:pt-20 lg:grid-cols-[1fr_320px] lg:items-end">
        <div><Link href="/#services" className="inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground transition hover:text-foreground"><ArrowLeft className="size-3.5" aria-hidden="true" />All services</Link><div className="mt-9 flex flex-wrap items-center gap-3"><span className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">{service.eyebrow}</span>{service.primary ? <span className="rounded-full border border-primary/25 bg-primary/10 px-2.5 py-1 font-mono text-[8px] uppercase tracking-[0.16em] text-primary">Primary specialty</span> : null}</div><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[.95] tracking-[-0.055em] sm:text-7xl">{service.headline}</h1><p className="mt-7 max-w-3xl text-base leading-8 text-muted-foreground sm:text-lg">{service.summary}</p><div className="mt-9 flex flex-wrap gap-3"><Link href={service.cta.href} className="inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">{service.cta.label}<ArrowRight className="size-4" aria-hidden="true" /></Link><Link href="/workflow-audit" className="inline-flex h-11 items-center rounded-lg border border-border bg-card px-5 text-sm font-medium">Start with a workflow audit</Link></div></div>
        <aside className="border-t border-border pt-7 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><div className="grid size-12 place-items-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><Icon className="size-5" aria-hidden="true" /></div><div className="mt-7 font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">Built for</div><p className="mt-3 text-sm leading-7 text-foreground/85">{service.targetCustomer}</p></aside>
      </header>

      <section aria-labelledby="problems-heading" className="border-y border-border bg-card/35"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Problems addressed</div><h2 id="problems-heading" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Where the operating drag shows up.</h2></div><div className="grid border-y border-border sm:grid-cols-2">{service.problems.map((problem, index) => <article key={problem.title} className="border-t border-border py-6 first:border-t-0 sm:border-l sm:px-6 sm:[&:nth-child(-n+2)]:border-t-0 sm:[&:nth-child(odd)]:border-l-0"><span className="font-mono text-[9px] text-primary">0{index + 1}</span><h3 className="mt-4 text-base font-medium">{problem.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{problem.description}</p></article>)}</div></div></div></section>

      <section aria-labelledby="deliverables-heading" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Example deliverables</div><h2 id="deliverables-heading" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A defined operating result—not a feature pile.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground">The exact result follows the workflow. These are representative deliverables, not a promise that every engagement includes every item.</p></div><ul className="grid border-y border-border sm:grid-cols-2">{service.deliverables.map((deliverable) => <li key={deliverable} className="flex min-h-20 items-center gap-3 border-t border-border py-4 first:border-t-0 sm:border-l sm:px-5 sm:[&:nth-child(-n+2)]:border-t-0 sm:[&:nth-child(odd)]:border-l-0"><Check className="size-4 shrink-0 text-primary" aria-hidden="true" /><span className="text-sm font-medium leading-6">{deliverable}</span></li>)}</ul></div></section>

      <section aria-labelledby="process-heading" className="border-y border-border bg-card/35"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Relevant process</div><h2 id="process-heading" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">The work is mapped before it is abstracted.</h2></div><ol className="mt-12 border-y border-border">{service.process.map((step, index) => <li key={step.title} className="grid gap-3 border-t border-border py-6 first:border-t-0 sm:grid-cols-[56px_220px_1fr] sm:items-start"><span className="font-mono text-[9px] text-primary">0{index + 1}</span><h3 className="text-sm font-medium">{step.title}</h3><p className="max-w-3xl text-sm leading-6 text-muted-foreground">{step.description}</p></li>)}</ol></div></section>

      <section aria-labelledby="examples-heading" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.56fr_1.44fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Relevant work</div><h2 id="examples-heading" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Proof points with their status intact.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground">These links explain what exists, what remains intended, and why the work is relevant. No concept is presented as completed client work.</p></div><div className="space-y-3">{examples.map(({ study, relevance }) => study ? <Link key={study.slug} href={`/work/${study.slug}`} className="group block rounded-xl border border-border bg-card/60 p-6 transition hover:border-primary/30"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-primary">{study.status}</span><h3 className="mt-2 text-xl font-semibold">{study.title}</h3></div><MoveUpRight className="size-4 text-muted-foreground transition group-hover:text-primary" aria-hidden="true" /></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{relevance}</p></Link> : null)}</div></div></section>

      <section id="engagement" aria-labelledby="engagement-heading" className="border-y border-border bg-card/35"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_1fr] lg:items-center"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Typical engagement range</div><h2 id="engagement-heading" className="mt-3 text-3xl font-semibold tracking-tight">Plan at the size of the current constraint.</h2><p className="mt-5 max-w-2xl text-base font-medium leading-7 text-foreground/90">{service.typicalEngagement.label}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{service.typicalEngagement.note}</p><p className="mt-3 max-w-2xl text-xs leading-5 text-muted-foreground">{engagementPlanningNote}</p></div><div className="rounded-xl border border-primary/25 bg-primary/10 p-6 sm:p-8"><Target className="size-5 text-primary" aria-hidden="true" /><h3 className="mt-6 text-xl font-semibold">Bring the current workflow, not a polished specification.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">The useful starting point is what happens today, who touches it, where it breaks, and what a better handoff would let the business do.</p><Link href={service.cta.href} className="mt-7 inline-flex h-11 items-center gap-2 rounded-lg bg-primary px-5 text-sm font-medium text-primary-foreground">{service.cta.label}<ArrowRight className="size-4" aria-hidden="true" /></Link></div></div></section>

      <section aria-labelledby="faq-heading" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><div className="font-mono text-[10px] uppercase tracking-[0.24em] text-primary">Frequently asked questions</div><h2 id="faq-heading" className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Before the first conversation.</h2></div><div className="border-y border-border">{service.faqs.map(({ question, answer }) => <details key={question} className="group border-t border-border py-5 first:border-t-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm font-medium"><span>{question}</span><span className="font-mono text-primary transition group-open:rotate-45" aria-hidden="true">+</span></summary><p className="max-w-3xl pt-4 text-sm leading-7 text-muted-foreground">{answer}</p></details>)}</div></div></section>
    </article>

    <SiteFooter><nav aria-label="Service pages" className="flex flex-wrap gap-x-5 gap-y-2 lg:justify-end">{publicServices.map((item) => <Link key={item.slug} href={`/services/${item.slug}`} aria-current={item.slug === service.slug ? "page" : undefined} className="transition hover:text-foreground aria-[current=page]:text-primary">{item.name}</Link>)}</nav></SiteFooter>
  </main>;
}
